### ISSUE TITLE
Offline quest progress on iPhone 5 and 5S isn't being saved.

### ISSUE THREAD

**Issue by karvozavr** [karvozavr/Quests#11]
iOS app v 0.3.1
This bug appear on iPhone 5 and 5S with iOS 9 and later on board.

Scenario:

1. With internet connection on, start a new quest. 
2. Start passing the quest.
3. Go to main menu and turn off the internet connection.
4. Proceed any number of steps. 
5. Go to main menu.
6. Turn on the internet connection.
7. Open app -> continue quest.

Expected result: progress is where it was after step 4.
Actual result: progress is where it was after step 3.   (Quest progress is on the point were we have gone offline. No offline progress saved.)

**Comment by karvozavr** [comment]
True for iPhone 5C as well.

**Comment by subject-name-here** [comment]
Working on it.

**Comment by subject-name-here** [comment]
Done.

**Comment by karvozavr** [comment]
@subject-name-here  The problem still appear, but only for Wi-Fi connection. While using 3G everything works fine.

**Comment by subject-name-here** [comment]
Fixed.

**Comment by karvozavr** [comment]
Seems to work now.

**Comment by karvozavr** [comment]
Tested on all major iOS releases for 5 and 5S. Working fine. Closing.
